### ISSUE TITLE
Is there a CVE Acknowledge/Whiteliste interface between Aqua and Harbor?

### ISSUE THREAD

**Issue by oliverbutanowitz** [aquasecurity/harbor-scanner-aqua#105]
Hi there!
I'm trying to find out, if - once i acknowledge CVEs within Aqua Enterprise (6.5.x) - those CVEs will also be whitelisted within harbor.
Within Aqua Enterprise, i could either acknowledge or even whitelist CVEs. But is this information delivered to Harbor?
I tried to set up a test-case, where i have simple Image with a critical CVE in a Harbor Project with activated "Deployment Security", after Acknowledgement of this CVE in Aqua and doing a rescan, i'm not able to pull this image. 
Just getting the message:
```
current image cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "Critical" or higher from running.' To continue with pull, please contact your project administrator to exempt matched vulnerabilities through configuring the CVE allowlist.
```
Am i missing some configuration steps, or is this information not transfered to Harbor for this scanner-plugin?
Aqua Enterprise: 6.5.x
Harbor-Scanner-Aqua: Latest
Harbor: 2.2.1
Thanks in advance for providing the information.

**Comment by danielpacak** [comment]
Hi @oliverbutanowitz The image assurance policies and CVEs acknowledged in Aqua Enterprise are not recognized by Harbor, and the Harbor Scanner Adapter for Aqua Enterprise in particular. This is because this service is just an implementation of [Pluggable Scanners API v1.0](https://github.com/goharbor/pluggable-scanner-spec), which does not specify how to pass such information to Harbor. It only dictates how to display vulnerabilities.

That said, additional work needs to be done by Harbor community to support the integration you described.

**Comment by oliverbutanowitz** [comment]
Thanks @danielpacak !
