### ISSUE TITLE
Feature Request: Pass additional scannercli arguments via configuration (env-file)

### ISSUE THREAD

**Issue by oliverbutanowitz** [aquasecurity/harbor-scanner-aqua#77]
Hi,

i'm searching for an option to pass additional command-line arguments to scannercli.
For example:
----
     --register                               # Register the image in the Aqua console
     --register-compliant             # Register the image in the Aqua console only if the scan reports compliance
     --policies strings                   # Force usage of provided image assurance policies (local scans only)
----
As i didn't find any possibility within the documentation, i hope it could be integrated.

**Comment by danielpacak** [comment]
Hi @oliverbutanowitz Would you provide more details what is the use case / workflow that you're trying to implement with Harbor, Aqua Enterprise, and the Harbor scanner adapter for Aqua?

We'd like to make sure that it's not something that is already available as configuration settings in Aqua Management Console and / or Harbor Portal before we add more arguments to the scannercli command. 

Ideally the scannercli should take all configuration settings from the Aqua server so any integration in your organisation based on Aqua has consistent policy baseline. Otherwise you may end up with different policies being evaluated in different places, which is confusing and hard to troubleshoot. For example, different vulnerabilities shown in Harbor Poratl versus Aqua Management Console.
Beyond that, some of the options that you've mentioned better end up being added to the Aqua product than this adapter service.

**Comment by oliverbutanowitz** [comment]
Hi @danielpacak,

thanks for your feedback.
The current scenario i'm working with is having K8s/OCP with an external harbor registry (local) per K8s-Cluster.
Once the Image build/promotion processes from our CIs are pushing Images the harbor registry, the image is immediatly being scanned by scannercli (taking the Aqua Enterprise default image assurance policy for configuration) and after scanning, the scan-results are visible in harbor. But those scan-results are not transfered to Aqua-Enterprise (option --register / --register-compliant), which is giving me the situation, that the image is accessable from K8s, but it is not yet known to Aqua-Enterprise. By default it would be scanned during night, in the next image-scan cycle of aqua.
For now i would either have to register this image by hand to aqua or do a rest-api-call somewhere from the CI.
It would be more logical to use the scannercli to register the image directly.
Similar it would be great to use the --policies option as different registries might have different scan-policies (internal-build registry vs. internal dockerhub-mirror etc.)

**Comment by danielpacak** [comment]
Thank you for the input @oliverbutanowitz I'll check with the product team if we can implement such functionality by means of configuring Aqua server. If not we'll proceed with adding the requested flags to this adapter service.

**Comment by danielpacak** [comment]
:wave: @oliverbutanowitz I've opened #82 which would allow you to enable image registration in Aqua console. See the commit description for more details. As explained in #81 we won't support `--policies` argument though.
